### ISSUE TITLE
Data Analysis - gender recognition sporadic behaviour, suddely error, revise code

### ISSUE THREAD

**Issue by mrkoubek** [mrkoubek/scraping-marathon-results#6]
Chapter 3.2 in Data Analysis Jupyter file, solve the sudden error after some change of previous code.

**Comment by mrkoubek** [comment]
In one of later versions of the Marathon_results_analysis.ipynb, this error needs some love:
![Analysis_3-2_error](https://user-images.githubusercontent.com/7693659/58738516-61fab000-8406-11e9-9d99-ee8ece0b1c88.png)

**Comment by mrkoubek** [comment]
Some indices were awry, this instance of an error was solved (in commit ccac0bd046aa35a2fc1487e6ea0eb034b51df382) by resetting the index on the df_names variable:

`df_names.reset_index(drop = True,inplace=True)`

prior to looping through the rows in the pictured code (in the gender recognition cell).

Also other warnings of pandas copy vs reference were eliminated by using .copy() where appropriate instead of referencing a new variable name to another variable name (i.e. not copying it):

`df_names = df_renamed.copy()`

**Comment by mrkoubek** [comment]
@JirkaZelenka please close this issue once you read the solution

**Comment by JirkaZelenka** [comment]
Read, accepted, retested, closed.
