### ISSUE TITLE
Data Analysis - df_final missing, revise code

### ISSUE THREAD

**Issue by mrkoubek** [mrkoubek/scraping-marathon-results#7]
df_final variable is suddenly missing in the middle, maybe a mistake in versioning, a relic from older versions before renaming a variable?

@JirkaZelenka  will look into this in the morning and polish it up.

![image](https://user-images.githubusercontent.com/7693659/58741194-98d8c200-8416-11e9-8e63-9fd440ff6808.png)

**Comment by JirkaZelenka** [comment]
Problem solved in commit https://github.com/mrkoubek/marathon-results-analysis/commit/599e47b05a18f38f976f2a9365c918a8c1ff5687  

One part of the dataset was not renamed due to rearranging the code in the last update.
Solved by adding another line of code with "df_new = df_old.copy()"
